# Generated by Django 4.2.30 on 2026-07-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='Free Size', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, default='Free Size', help_text="Comma-separated sizes, e.g., 'S, M, L, XL'", max_length=255),
        ),
    ]
